In [1]:
import torch

x = torch.empty(1)
print(x)

tensor([-55.9499])


In [2]:
x = torch.empty(3)
print(x)

tensor([2.2664e-02, 3.1892e-41, 2.3046e+01])


In [3]:
x = torch.empty(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.empty(2,3,4)
print(x)

tensor([[[ 2.6239e-32,  4.3384e-41,  2.6239e-32,  4.3384e-41],
         [ 4.4842e-44,  0.0000e+00,  1.5695e-43,  0.0000e+00],
         [-3.0050e-30,  7.0065e-45,  0.0000e+00,  0.0000e+00]],

        [[ 1.4013e-45,  0.0000e+00,  2.3048e+01,  3.1892e-41],
         [ 1.8881e-36,  4.3384e-41,  2.3048e+01,  3.1892e-41],
         [ 4.2607e-08,  3.3088e-09,  8.4078e-45,  0.0000e+00]]])


In [5]:
x = torch.ones(2,2, dtype=torch.int)
print(x.dtype)

x = torch.ones(2,2, dtype=torch.double)
print(x.dtype)

torch.int32
torch.float64


In [6]:
x.size()

torch.Size([2, 2])

In [7]:
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [8]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x,y)

z = x+y
z = torch.add(x,y)

print(z)

tensor([[0.4499, 0.3170],
        [0.6968, 0.7237]]) tensor([[0.0560, 0.9674],
        [0.4812, 0.1086]])
tensor([[0.5059, 1.2845],
        [1.1780, 0.8323]])


In [9]:
# inplace addn

y.add_(x)
print(y)

tensor([[0.5059, 1.2845],
        [1.1780, 0.8323]])


In [10]:
# other operations

# torch.sub()
# torch.mul()
# torch.div()

# for inplace use y.sub_(x)

In [11]:
x = torch.rand(4,4)
print(x)
# convert into 1d vector
y=x.view(16)
print(y)

y = x.view(-1,8)
print(y.size())

tensor([[0.0491, 0.9464, 0.0078, 0.3403],
        [0.6345, 0.3419, 0.7150, 0.9393],
        [0.6586, 0.1979, 0.9068, 0.3450],
        [0.0583, 0.9259, 0.2172, 0.7981]])
tensor([0.0491, 0.9464, 0.0078, 0.3403, 0.6345, 0.3419, 0.7150, 0.9393, 0.6586,
        0.1979, 0.9068, 0.3450, 0.0583, 0.9259, 0.2172, 0.7981])
torch.Size([2, 8])


In [17]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [18]:
a += 1
print(a)
print(b)

#only if tensor is in cpu then they share same memory location so updating obe will also update the other

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
# cuda toolkit

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


In [20]:
device

device(type='cuda')